techniques = [
    {
        name: "Adaptive Menus",
        description: "Adaptive menus are menus presenting selectable options considering a recommandation process. Multiple variants of adaptive menus will be presented to you during this experiment. Read carefully each menu description and compare each pair to select your preference."
    },
];

descriptions = [ { name: 'Blinking Menu',
    description: 'Description of Blinking Menu' },
  { name: 'Blurring Menu',
    description: 'Description of Blurring Menu' },
  { name: 'Bolding Menu',
    description: 'Description of Bolding Menu' },
  { name: 'Bowing Menu',
    description: 'Description of Bowing Menu' },
  { name: 'Bubbling Menu',
    description: 'Description of Bubbling Menu' },
  { name: 'Cloud Menu', description: 'Description of Cloud Menu' },
  { name: 'Ephemeral Menu',
    description: 'Description of Ephemeral Menu' },
  { name: 'Evanescent Menu',
    description: 'Description of Evanescent Menu' },
  { name: 'Fish-eye Menu',
    description: 'Description of Fish-eye Menu' },
  { name: 'Fish-eye colored menu',
    description: 'Description of Fish-eye colored menu' },
  { name: 'Flower Menu',
    description: 'Description of Flower Menu' },
  { name: 'Font-changing Menu',
    description: 'Description of Font-changing Menu' },
  { name: 'Frequency-based Menu',
    description: 'Description of Frequency-based Menu' },
  { name: 'Glowing Menu',
    description: 'Description of Glowing Menu' },
  { name: 'Greyscaling Menu',
    description: 'Description of Greyscaling Menu' },
  { name: 'Heatmap Menu',
    description: 'Description of Heatmap Menu' },
  { name: 'Highlighting Menu',
    description: 'Description of Highlighting Menu' },
  { name: 'Hyperbolic Menu',
    description: 'Description of Hyperbolic Menu' },
  { name: 'In-context Appearing Menu',
    description: 'Description of In-context Appearing Menu' },
  { name: 'Italiczing Menu',
    description: 'Description of Italiczing Menu' },
  { name: 'Morphing Menu',
    description: 'Description of Morphing Menu' },
  { name: 'Out-context Disappearing Menu',
    description: 'Description of Out-context Disappearing Menu' },
  { name: 'Patined Menu',
    description: 'Description of Patined Menu' },
  { name: 'Polymodal Menu',
    description: 'Description of Polymodal Menu' },
  { name: 'Prediction-by-bar Menu',
    description: 'Description of Prediction-by-bar Menu' },
  { name: 'Prediction-by-color Menu',
    description: 'Description of Prediction-by-color Menu' },
  { name: 'Prediction-by-line Menu',
    description: 'Description of Prediction-by-line Menu' },
  { name: 'Prediction-by-rainbow Menu',
    description: 'Description of Prediction-by-rainbow Menu' },
  { name: 'Prediction-by-scale Menu',
    description: 'Description of Prediction-by-scale Menu' },
  { name: 'Probability-based Menu',
    description: 'Description of Probability-based Menu' },
  { name: 'Pulsing Menu',
    description: 'Description of Pulsing Menu' },
  { name: 'Pushpin Menu',
    description: 'Description of Pushpin Menu' },
  { name: 'Rainbow menu',
    description: 'Description of Rainbow menu' },
  { name: 'Rating Menu',
    description: 'Description of Rating Menu' },
  { name: 'Rotating Menu',
    description: 'Description of Rotating Menu' },
  { name: 'Smart Menu', description: 'Description of Smart Menu' },
  { name: 'Split Menu with Arrowbar',
    description: 'Description of Split Menu with Arrowbar' },
  { name: 'Split Menu with Replication',
    description: 'Description of Split Menu with Replication' },
  { name: 'Split Menu with Scrollbar',
    description: 'Description of Split Menu with Scrollbar' },
  { name: 'Split Menu without replication',
    description: 'Description of Split Menu without replication' },
  { name: 'Square Menu',
    description: 'Description of Square Menu' },
  { name: 'Ste-by-step Menu',
    description: 'Description of Ste-by-step Menu' },
  { name: 'Temporal Menu',
    description: 'Description of Temporal Menu' },
  { name: 'Time-based Menu',
    description: 'Description of Time-based Menu' },
  { name: 'Transparency Menu',
    description: 'Description of Transparency Menu' },
  { name: 'Tree Menu', description: 'Description of Tree Menu' },
  { name: 'Twisting Menu',
    description: 'Description of Twisting Menu' },
  { name: 'Underlying Menu',
    description: 'Description of Underlying Menu' },
  { name: 'Weared Menu',
    description: 'Description of Weared Menu' } ]
