techniques = [
    {
        name: "Adaptive Menus",
        description: "Adaptive menus are menus presenting selectable options considering a recommandation process. Multiple variants of adaptive menus will be presented to you during this experiment. Read carefully each menu description and compare each pair to select your preference."
    },
];

descriptions = [ { name: 'Blinking Menu',
    description: 'Predicted menu items are blinking to make them more salient' },
  { name: 'Blurring Menu',
    description: 'Menu items with low prediction are blurred to make them less salient' },
  { name: 'Bolding Menu',
    description: 'Bolding menus are another form where predicted items are boldfaced. A split menu, a bolding menu, an adaptable menu, and a traditional menu were compared for a normal screen. This study showed that the adaptable menu outperformed the other menus in terms of overall performance and subjective satisfaction. Different forms of emphasizing items in the predicted window may be investigated, such as by highlighting, by underlying, by bolding, by italicizing, etc. The design space that will be later defined will enable us to investigate these options more extensively.' },
  { name: 'Bowing Menu',
    description: 'Menu items with high prediction are framed into a box' },
  { name: 'Bubbling Menu',
    description: 'Bubbling menus represent a design for cascading drop-down menus aimed at accelerating the selection of the frequently used items by directly jumping to them one by one. To this end, two techniques are combined: the bubble cursor, whose size dynamically changes as the cursor moves and selects the target within the closest distance, especially for frequently-based items; and directional mouse-gesture techniques, which accelerate reaching predicted items.' },
  { name: 'Cloud Menu', description: 'Cloud Menus are a split adaptive menu for small screens where the predicted menu items are arranged in a circular tag cloud with a location consistent with their corresponding position in the static menu and a font size depending on their prediction level. An empirical study suggests that cloud menus reduce item selection time and error rate when prediction is correct without penalizing it when prediction is incorrect, compared to two baselines: a non-adaptive static menu and an adaptive linear menu.' },
  { name: 'Ephemeral Menu',
    description: 'Ephemeral menus is an adaptive temporal menu where the gradual onset was used in order to display non-predicted items. At opening the menu, user finds predicted items and after a delay of 500ms remaining items appear gradually.' },
  { name: 'Evanescent Menu',
    description: 'Evanescent menus are adaptive menu where the prediction window is first presented superimposed to the initial menu and then progressively made transparent to reveal the menu, thus enabling the user to select a predicted item if it belongs to the prediction window and the initial menu after.' },
  { name: 'Fish-eye Menu',
    description: 'Fish-eye menus display items with a font size that increases or decreases depending on the distance with respect to cursor position: the closer, the larger, the further, the smaller. Per se, fish-eye menus are not adaptive since their layout does not change depending on predicted items. They are able to increase the selection area of any item, which might be useful for predicted items.' },
  { name: 'Fish-eye colored menu',
    description: 'Fish-eye menus display items with a font size that increases or decreases depending on the distance with respect to cursor position: the closer, the larger, the further, the smaller. Per se, fish-eye menus are not adaptive since their layout does not change depending on predicted items. They are able to increase the selection area of any item, which might be useful for predicted items.' },
  { name: 'Flower Menu',
    description: 'Flower menus extend marking menus with opportunity to draw straight lines or curved ones into the eight cardinal directions of a compass, which can optionally be terminated by bended, cusped, and pig-tail endings. A comparative study of flower, linear and polygon menus shows that polygon and flower menus offer better performance for learning in expert mode as compared to linear menus.' },
  { name: 'Font-changing Menu',
    description: 'Menu items with high prediction see their font changed to make them more salient' },
  { name: 'Frequency-based Menu',
    description: 'Frequency-based menus sort items by decreasing order of frequency, depending on the end user’s actions, thus promoting MFU. They are probably the first manifestation of adaptive menu in history during the 1980’s with the probability-based menus.' },
  { name: 'Glowing Menu',
    description: 'Menu items with high prediction are subject to an after-glow visual effect' },
  { name: 'Greyscaling Menu',
    description: 'Menu items with low prediction become more light grey as they are less predictable' },
  { name: 'Heatmap Menu',
    description: 'The more predictable the menu item is, the warmer the color is' },
  { name: 'Highlighting Menu',
    description: 'Highlighting menus highlight predicted items by contrasting them with respect to normal items appearing in the static menu.' },
  { name: 'Hyperbolic Menu',
    description: 'Hyperbolic menus is a Focus + Context technique for displaying and manipulating large hierarchies. It displays several hierarchy levels at once according to a hyperbolic tree which minimizes screen usage. All menu items are displayed on this hyperbolic tree. Since parts of the hyperbolic view are expanding and collapsing depending on the position of the cursor, menu items are never displayed at the same place, thus inducing spatial instability, which is difficult to use for novice users and without fine visio-motor coordination.' },
  { name: 'In-context Appearing Menu',
    description: 'In-Context Disappearing (ICD) approach has been applied to menus for small screens: at opening the static menu, the end user finds a superposition of the full list of items with the prediction window prompting predicted items. This latter contains three predicted items and disappears gradually. The presentation of predicted items in the prediction window remains homogeneous, thus preserving spatial stability.' },
  { name: 'Italiczing Menu',
    description: 'Menu items with high prediction are formatted into italics' },
  { name: 'Morphing Menu',
    description: 'Morphing menus change the font size of each menu item depending on its prediction: the font size is increased, respectively decreased, if the prediction is high, respectively low. While morphing menus preserve spatial stability, they facilitate selecting accurately-predicted items, but complexify selecting items with low or inaccurate prediction. Morphing menus made manipulation easier with enlarged activation areas in cascading menus. The objective was to eliminate the explicit delay for activation found in several implementations.' },
  { name: 'Out-context Disappearing Menu',
    description: 'Out-of-Context Disappearing (OCD) approach is the inverse of ICD: at opening, the prediction window is immediately displayed with the predicted items, like in a split menu; after 500 msec, the complete menu is gradually displayed from the back, thus replacing the prediction window.' },
  { name: 'Patined Menu',
    description: 'Menu items are patined based on their prediction' },
  { name: 'Polymodal Menu',
    description: 'Polymodal Menus are adaptive graphical menus in which any menu item can be selected graphically (by pointing), vocally (by voice recognition), tactilely (by touching), gesturally (by issuing a gesture representing the menu), or any combination of them. Predicted menus are rendered by graphical or vocal prediction window.' },
  { name: 'Prediction-by-bar Menu',
    description: 'Menu items with high prediction are formatted with a line, a bar, or a scale to indicate their level of prediction' },
  { name: 'Prediction-by-color Menu',
    description: 'Menu items with high prediction are formatted with a line, a bar, or a scale to indicate their level of prediction' },
  { name: 'Prediction-by-line Menu',
    description: 'Menu items with high prediction are formatted with a line, a bar, or a scale to indicate their level of prediction' },
  { name: 'Prediction-by-rainbow Menu',
    description: 'Menu items with high prediction are formatted with a line, a bar, or a scale to indicate their level of prediction' },
  { name: 'Prediction-by-scale Menu',
    description: 'Menu items with high prediction are formatted with a line, a bar, or a scale to indicate their level of prediction' },
  { name: 'Probability-based Menu',
    description: 'Probability-based menus sort items by decreasing probability of selection: most popular items are positioned near the beginning of the menu. During the initial stages of practice, probability- based menus produce faster mean selection times than the static menu, the random menu (where items are randomly arranged), and the alphabetic menu (where items are sorted by increasing alphabetical order). After some practice, the static menu becomes better than the probability-based menu. End users remember easily the item position in the menu, indicating that spatial stability is an important factor in increasing the efficiency of menu selection.' },
  { name: 'Pulsing Menu',
    description: 'Menu items with high prediction are pulsed to make them more salient' },
  { name: 'Pushpin Menu',
    description: 'Menu items with high prediction are blocked in the menu with a pin to make them permanent' },
  { name: 'Rainbow menu',
    description: 'Menu items with high prediction are emphasized with a rainbow visual effect' },
  { name: 'Rating Menu',
    description: 'Menu items are presented with a rating bar depending on their level of prediction' },
  { name: 'Rotating Menu',
    description: 'Menu items with high prediction are rotated once to attract attention' },
  { name: 'Smart Menu', description: 'Smart menus, featured in Microsoft Office 2003, initially show only the most commonly used items and all the available items by clicking on the arrow at the bottom of the smart menu to expand it. Smart menus track how often an end user invokes each item, in order to predict frequently-used and recently used menu items. Smart menus provide beginners with a starting guided path toward learning a new UI. Menus become adaptive when they reflect the users’ work habits. In short, a MFU scheme automatically hides unused items.' },
  { name: 'Split Menu with Arrowbar',
    description: 'Split menus assemble a prediction window (here, a topmost area promoting a small list of predicted items, typically 2-3) and a static menu. Menu items are initially predicted according MFU scheme and later on expanded to other schemes such as MRU, DOI, or any combination of them. Any menu item appears in either the static part or in the predicted window, which may confuse users who constantly oscillate between the two areas to find their item. Split menus with replication restore spatial stability: the prediction window remains as stated before but the second part remains unaltered, thus enabling end users to always refer to the static menu as they know it.' },
  { name: 'Split Menu with Replication',
    description: 'Split menus assemble a prediction window (here, a topmost area promoting a small list of predicted items, typically 2-3) and a static menu. Menu items are initially predicted according MFU scheme and later on expanded to other schemes such as MRU, DOI, or any combination of them. Any menu item appears in either the static part or in the predicted window, which may confuse users who constantly oscillate between the two areas to find their item. Split menus with replication restore spatial stability: the prediction window remains as stated before but the second part remains unaltered, thus enabling end users to always refer to the static menu as they know it.' },
  { name: 'Split Menu with Scrollbar',
    description: 'Split menus assemble a prediction window (here, a topmost area promoting a small list of predicted items, typically 2-3) and a static menu. Menu items are initially predicted according MFU scheme and later on expanded to other schemes such as MRU, DOI, or any combination of them. Any menu item appears in either the static part or in the predicted window, which may confuse users who constantly oscillate between the two areas to find their item. Split menus with replication restore spatial stability: the prediction window remains as stated before but the second part remains unaltered, thus enabling end users to always refer to the static menu as they know it.' },
  { name: 'Split Menu without replication',
    description: 'Split menus assemble a prediction window (here, a topmost area promoting a small list of predicted items, typically 2-3) and a static menu. Menu items are initially predicted according MFU scheme and later on expanded to other schemes such as MRU, DOI, or any combination of them. Any menu item appears in either the static part or in the predicted window, which may confuse users who constantly oscillate between the two areas to find their item. Split menus with replication restore spatial stability: the prediction window remains as stated before but the second part remains unaltered, thus enabling end users to always refer to the static menu as they know it.' },
  { name: 'Square Menu',
    description: 'Square Menus are re-layouting menu items of the pull-down menus into square regions in order to improve their selection performance. They performed a large analysis of several research studies to propose the Search, Decision, and Pointing (SDP) model. Square Menus improve specifically pointing performance, especially for experts.' },
  { name: 'Ste-by-step Menu',
    description: 'Step-by-Step Menus displays at each level of the hierarchy the prediction window and offers to select the menu item leading to the next level of the target path.' },
  { name: 'Temporal Menu',
    description: 'Temporal menus introduce a temporal dimension by displaying items on two stages: at opening, the menu displays only predicted items, after a delay of 170ms, non-predicted items appear. This menu maintains spatial stability, thus helping the end user to maintain a mental model of the menu. Transposing temporal menu to smartphone is not straightforward because all items cannot be displayed on a single screen. Any predicted item located on the sub-sequent screens requires a cognitive effort to explore the whole set of items.' },
  { name: 'Time-based Menu',
    description: 'Menu items with high prediction are re-arranged depending on the time in the day they are selected' },
  { name: 'Transparency Menu',
    description: 'Menu items with low prediction are formatted with a transparency level reflecting their level of prediction' },
  { name: 'Tree Menu', description: 'Menu items are re-arranged into sub-trees depnding on their level of prediction (e.g., low, medium, high)' },
  { name: 'Twisting Menu',
    description: 'Menu items with high prediction are twisted to make them more attention-catching' },
  { name: 'Underlying Menu',
    description: 'Menu items with high prediction are underlined' },
  { name: 'Weared Menu',
    description: 'Menu items are presented according to a wearing pattern : the more often they are used, the more usaged they look like, the older the menu item is, the more rusty it looks like' } ]
